---
name: Joshua
surname: Ankeny
position: "Natural Resources Technician I"
address: "8110 US HWY 12, Glenoma, WA 98336"
#profilepic: "./img/profile.jpg"
phone: 814-289-9149
email: "joshankeny10@gmail.com"
linkedin: joshua-ankeny
github: joshankeny
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 990000
aboutme: Over the past three years I have been working for Tacoma Power in various capacities. My work with Tacoma Power began as a field technician performing various salmonid related field operations. Through the COVID pandemic, my job duties shifted to allow more focus on data analysis, data visualization and continued education with various data software and languages. During this period I have expanded my portfolio to include the advanced use of R, RShiny, Tableau, Snowflake, FME, Python and ESRI Products. Though I graduated with a M.Sc. Degree in Wildlife and Fisheries Resources, I have always had a deep-seated passion for data science, data visualization and automation. My passion for this field of work is expressed within this CV made wholly using R. 
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
require(xfun)
packages <- c('vitae','tibble','magrittr','here','readr','glue','RefManageR')
setwd("C:/Users/Jankeny/Documents/CV")
xfun::pkg_attach2(packages, message = FALSE)
source("r/data.r")
```

# Employment

```{r EMPLOYMENT, echo = FALSE}

work %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where,
    .protect = FALSE
  )
  
```

# Education

```{r EDUCATION, echo = FALSE}

edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = GPA,
    when = glue::glue("{startYear} --> {endYear}",.na = "")
  )
  
```

# Skills

```{r SKILLS, echo = FALSE}

skills %>%
  detailed_entries(
    with = area,
    what = skills
  )
  
```

# Shiny Applications

```{r HONORS, echo = FALSE}

shinyapps %>%
  detailed_entries(
    with = app,
    what = click,
    .protect = FALSE
  )
  
```

# Research Experience

```{r RESEARCH_EXPERIENCE, echo = FALSE}

research_experience %>%
  detailed_entries(
    with = title,
    what = role,
    why = detail,
    where = where,
    .protect = FALSE
  )
  
```

<!-- # Certifications -->

<!-- ```{r CERTIFICATIONS, echo = FALSE} -->

<!-- certifications %>% -->
<!--   detailed_entries( -->
<!--     what = cert -->
<!--   ) -->

<!-- ``` -->




# Publications

```{r PUBLICATIONS, echo = FALSE}
bibliography_entries("my_publications.bib", "Publications")

```

# References

```{r REFERENCES, echo = FALSE}

references %>%
  detailed_entries(
    with = name,
    what = title,
    why = contact
  )
  
```