---
author: Joshua Ankeny
return-address: 
  - 8110 US Highway 12
  - Glenoma, WA 98336
address:
  - Human Resources Department
  - 747 Market Street
  - Tacoma, WA 98402-3764

papersize: letter
date: NULL
subject: Human Resources Analyst, Senior - Workforce Data Analyst
opening: Dear Human Resources Department,
closing: Best Regards,
signature: Joshua Ankeny

output: komaletter::komaletter
---

My name is Joshua Ankeny and I am a Natural Resources Technician I with the City of Tacoma. I currently work on the Cowlitz River Project for the TPU - Power - Generation - Natural Resources team. Prior to my employment with the City, I was performing contract work for Tacoma Power on the Cowlitz River Project. In my time as a contractor I received outstanding employee reviews and quickly climbed until I was hired on as a FTE for the City of Tacoma. Even though my rapid transition to a City of Tacoma employee was a great accomplishment, my job duties have remained static. Through the COVID pandemic, my job duties shifted to allow more focus on data analysis, data visualization and continued education with various data software and languages. During this period I have expanded my portfolio to include the advanced use of R, RShiny, Tableau, Snowflake, FME, Python and ESRI Products. While you review my CV I ask you to disregard the focus of my degrees and instead consider the other educational experiences that I gathered from obtaining them. Both my undergraduate and graduate degrees involved extensive education in statistical analysis, data management, data manipulation and data visualization. Both degrees required my utmost focus and were finished in a timely manner with elaborate exit theses. Additionally, my graduate degree also provided two years of supervisory experience. My education alongside my data analyst experiences have prepared me to excel in the role of Human Resources Analyst, Senior - Workforce Data Analyst.

At the initiation of the COVID-19 pandemic, I had the opportunity to further my education in data analysis and data visualization. I am highly self-motivated and saw this as an opportunity to expand my knowledge of data analysis. I quickly picked up R, SQL, Python, HTML, LaTeX, CSS and JavaScript. I also became well versed in data engineering software (i.e., Snowflake, FME, Databricks and AWS) and dashboarding software (i.e., RShiny and Tableau). These tools allowed me to construct various RShiny Web Applications, RMarkdown automated reports, Tableau Dashboards, Excel spreadsheets and ArcGIS products. I became a point of contact for data visualization projects and database management solutions. My proudest accomplishment while in this position was the completion of the Cowlitz Runtime App. The Cowlitz Runtime App is a RShiny web application with extensive background analysis. Within the application, I present salmonid data collected from the Cowlitz River Project and use it to predict future salmonid run sizes and timing. In addition to run predictions, I also outline disbursement of adult salmonids within the river basin to meet a public outreach goal. Examples of these products will be compiled in a digital file as part of my application.

In closing, I feel that I am a great fit for the Human Resources Analyst, Senior - Workforce Data Analyst position. I bring with me a suite of skills that will greatly benefit the project. I am excited to be a part of the Human Resources team and represent the City of Tacoma. Any additional information can be found on my curriculum vitae or by contacting me.
