---
name: Joshua
surname: Ankeny
position: "Fisheries Technician II"
address: "8110 US HWY 12, Glenoma, WA 98336"
profilepic: "./img/profile.jpg"
phone: 814-289-9149
email: "joshankeny10@gmail.com"
linkedin: joshua-ankeny
github: joshankeny
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 990000
aboutme: Over the past 3 years I have been working as a Pacific States Marine Fisheries Commission contractor for Tacoma Power. I regularly perform various fisheries technician duties (i.e., spawning ground surveys, PIT tagging, biosampling, fish identification and enumeration, etc.). In the past 2 years my duties have shifted to allow for more focus on data analysis, data visualization and continued education with various data softwares. I primarily use R, ArcGIS Pro, Tableau and Snowflake to complete various data visualization projects. I have a deep seeded passion for data science, data visualization and automation.
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
require(xfun)
packages <- c('vitae','tibble','magrittr','here','readr','glue','RefManageR')
setwd("C:/Users/Jankeny/Documents/CV")
xfun::pkg_attach2(packages, message = FALSE)
source("r/data.r")
```

# Employment

```{r EMPLOYMENT, echo = FALSE}

work %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where,
    .protect = FALSE
  )
  
```

# Education

```{r EDUCATION, echo = FALSE}

edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = GPA,
    when = glue::glue("{startYear} --> {endYear}",.na = "")
  )
  
```

# Skills

```{r SKILLS, echo = FALSE}

skills %>%
  detailed_entries(
    with = area,
    what = skills
  )
  
```

# Shiny Applications

```{r HONORS, echo = FALSE}

shinyapps %>%
  detailed_entries(
    with = app,
    what = click,
    .protect = FALSE
  )
  
```

# Research Experience

```{r RESEARCH_EXPERIENCE, echo = FALSE}

research_experience %>%
  detailed_entries(
    with = title,
    what = role,
    why = detail,
    where = where,
    .protect = FALSE
  )
  
```

# Certifications

```{r CERTIFICATIONS, echo = FALSE}

certifications %>%
  detailed_entries(
    what = cert
  )
  
```




# Publications

```{r PUBLICATIONS, echo = FALSE}
bibliography_entries("my_publications.bib", "Publications")

```

# References

```{r REFERENCES, echo = FALSE}

references %>%
  detailed_entries(
    with = name,
    what = title,
    why = contact
  )
  
```